### ISSUE TITLE
 How my data  format is?

### ISSUE THREAD

**Issue by zhengsw** [inikdom/neural-chatbot#11]
I use this do :$ python util/sequencelengthplotter.py --data_dir="path/to/raw_data_files"

Traceback (most recent call last):
  File "util/sequencelengthplotter.py", line 98, in <module>
    main()
  File "util/sequencelengthplotter.py", line 67, in main
    plotHistoLengths("target lengths", target_lengths)
  File "util/sequencelengthplotter.py", line 93, in plotHistoLengths
    plt.xlim(0,max(lengths))
ValueError: max() arg is an empty sequence

how "data_source_test.txt" &  "data_target_test.txt"  file's  data  format may i need.
Has any data template ?

**Comment by inikdom** [comment]
So, I think I made a (bad) assumption that the optimiser would be run first, which calls dataprocessor.py to do work on it. The processed files from the data processor are what it's looking for. I am working on an update now to automatically call the dataprocessor from sequenceplotter.py.

**Comment by inikdom** [comment]
Ok, I've resolved this with: e6675a189ffd226fcafa5300e97bfd680f91be09. You should run `$ python sequencelengthplotter.py --raw_data_dir="path_to_your_raw_text_data"`  It will first process the data, then it will plot the histograms for you of sequence lengths.

It will use the `max_data_sizes` values in the config file. (be careful to set those).

If you have further questions or if something doesn't feel right, feel free to open another issue.

**Comment by zhengsw** [comment]
when i run 
$ python sequencelengthplotter.py --raw_data_dir="data"

Train/Test files not detected, creating now...
Checking to see what data processor needs to do...
Obtaining raw text conversation files...
Building vocab...
Traceback (most recent call last):
  File "sequencelengthplotter.py", line 118, in <module>
    main()
  File "sequencelengthplotter.py", line 58, in main
    data_processor.run()
  File "/home/test/neural-chatbot-master/util/dataprocessor.py", line 100, in run
    with open(text_file, "r+") as f:
IOError: [Errno 21] Is a directory: 'data/test'



----------------------------------------------------------------------
there just two dir( test & train )in --data file.
i can't find any file in data/test and data/train dir .
