### ISSUE TITLE
so, we cannot directly use the dataet from seq2seq-chatbot/tree/master/data/raw , right?

### ISSUE THREAD

**Issue by loveJasmine** [inikdom/neural-chatbot#12]

**Comment by inikdom** [comment]
Actually, you should be able to. I never really thought about it, but it is in the same format. You may need to try different bucket sizes. To run it, place it somewhere like:

`data/raw/`

You can then run:

``python train.py --raw_data_dir="data/raw/"``

I will need to update the documentation to explain this a bit better.

**Comment by domerin0** [comment]
I've commited a dataset which will work. I'm closing this issue now, but you're welcome to re-open or start a new one if there are other problems/ if you have questions.
