### ISSUE TITLE
Hi i got a ImportError

### ISSUE THREAD

**Issue by vtorrecillas** [inikdom/neural-chatbot#14]
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    import models.chatbot
  File "/home/vinicius_torrecillas/neural-chatbot/models/chatbot.py", line 13, in <module>
    from tensorflow.python.ops import rnn, rnn_cell, seq2seq
ImportError: cannot import name rnn_cell

how can i fix this?

**Comment by inikdom** [comment]
Hello,

Can you tell me what version of TensorFlow you are using? The import statement have changed I think. I will attempt to fix them for the latest version, but I suspect there will need to be other code changes as well to update it.

**Comment by domerin0** [comment]
I made some significant changes to the project (for TF 1.2). If this or another issue persists, feel free to re-open the issue.
